### ISSUE TITLE
Améliorer la gestion des préfixes

### ISSUE THREAD

**Issue by KittyGiraudel** [nico3333fr/ROCSSTI#9]
Le mixin pour gérer les préfixes constructeurs est un peu brutal à l'heure actuel. Il est possible de l'améliorer afin de lui permettre de ne générer que les préfixes demandés, et pas systématiquement les 4.

``` scss
@mixin vendor-prefix($property, $value, $prefixes: webkit moz ms o) {
  @if $prefixes {
    @each $prefix in $prefixes {
      #{'-' + $prefix + '-' + $property}: $value;
    }
  }
  #{$property}: $value;
}
```

L'utilisation se fait donc comme cela :

``` scss
.cut {
  word-wrap: break-word;
  @include vendor-prefix(hyphens, auto, webkit moz ms);
}
```
